### ISSUE TITLE
Create Resources & Costs

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/ProjectNeon#151] opened 2019-09-20 05:42 UTC
Role: DESIGN

Size: 1 unit / 15 min

**Comment by 0crat** [comment] 2019-09-20 06:11
The job [#151](https://github.com/enigmadragons/projectneon/issues/151) assigned to @kazamaru[/z](https://www.0crat.com/u/kazamaru), here is [why](https://www.0crat.com/footprint/CN3V1M4AU/9a5afc63-14b1-4b31-83cf-9e8a2837a8dd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @kazamaru[/z](https://www.0crat.com/u/kazamaru) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment] 2019-09-20 06:13
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment] 2019-09-20 06:14
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Closed** 2019-09-21 03:55 UTC
Labels: design

**Comment by 0crat** [comment] 2019-09-21 04:12
@kazamaru[/z](https://www.0crat.com/u/kazamaru) the issue is closed not by @SilasReinagel (its creator); I won't close the order; please, re-open it and ask @SilasReinagel to close it

**Comment by 0crat** [comment] 2019-09-25 06:39
@kazamaru[/z](https://www.0crat.com/u/kazamaru) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.
