### ISSUE TITLE
Status effect Icons get oversized

### ISSUE THREAD

**Issue by MichaelElkan** [EnigmaDragons/ProjectNeon#1494] opened 2020-10-12 23:44 UTC
![Damage over time graphic bug](https://user-images.githubusercontent.com/12078012/95799450-b7b1be80-0cc2-11eb-9356-e66fa145cb1c.png)
![Status effect Icons Oversized](https://user-images.githubusercontent.com/12078012/95799456-bc767280-0cc2-11eb-9be6-d23161940307.png)
![Other status effect graphic bugs](https://user-images.githubusercontent.com/12078012/95799464-c13b2680-0cc2-11eb-8fb1-86acd972f7dc.png)

**Comment by SilasReinagel** [comment] 2020-10-13 01:12
This is a duplicate of EnigmaDragons/ProjectNeon#1465

**Closed** 2020-10-13 01:12 UTC
Labels: bug
